// survivalEras.js
// Era-specific Squig Survival content. Shared images stay in the engine.

const DAY_ONE_LORE_LINES = [
  "🌀 {player} tries coffee for the first time and decides it is \"spicy water.\"",
  "🛒 {player} discovers grocery carts and insists they are \"metal steeds.\"",
  "📱 {player} scrolls for three hours and calls it \"research.\"",
  "🍕 {player} argues pineapple improves portals.",
  "🧦 {player} collects socks and declares them \"Earth skins.\"",
  "🎧 {player} hears lo-fi beats and refuses to stop vibing.",
  "🚌 {player} boards the wrong bus and calls it \"quest mode.\"",
  "🧴 {player} learns sunscreen exists and applies it to a hat.",
  "🧊 {player} meets ice for the first time and distrusts it.",
  "🪙 {player} trades a shiny pebble for a real coin and feels powerful.",
  "🧠 {player} reads a self-help book and still chooses chaos.",
  "🐸 {player} tries to befriend a frog and gets judged.",
  "🕶️ {player} buys sunglasses and claims \"the sun is rude.\"",
  "🍔 {player} believes burgers are a cultural handshake.",
  "🧼 {player} learns \"soap\" and becomes briefly unstoppable.",
  "🚦 {player} stares at traffic lights like they're speaking in riddles.",
  "📦 {player} discovers cardboard boxes are \"cozy portals.\"",
  "💤 {player} naps in public and calls it \"social camouflage.\"",
  "🎢 {player} rides a rollercoaster and rethinks gravity.",
  "📺 {player} watches a sitcom and decides humans are \"strange but funny.\"",
  "The day is calmer when {player} decides to simply people-watch.",
  "A vending machine teaches {player} the meaning of patience.",
  "Someone hands {player} a receipt and they keep it as a trophy.",
  "A pigeon stares back at {player}. They negotiate a truce.",
  "Today, {player} discovers escalators and calls them \"lazy stairs.\"",
  "An elevator stops. {player} bows out of respect.",
  "A hoodie becomes a ceremonial robe for {player}.",
  "The word \"brunch\" confuses {player} for 12 minutes.",
  "At the crosswalk, {player} misreads the tiny person as a warning sprite.",
  "On a walk, {player} decides sidewalks are \"ground rivers.\"",
  "A delivery driver nods at {player}. Diplomatic relations established.",
  "A subway map makes {player} feel briefly omniscient.",
  "A paper clip becomes a relic in {player}'s pocket.",
  "{player} declares socks optional and is immediately corrected by a breeze.",
  "A park bench adopts {player} for a quiet moment.",
  "The moon gets a casual wave from {player}. It does not wave back.",
  "Today, {player} learns the power of a good playlist.",
  "A rainy day turns {player}'s footsteps into percussion.",
  "A QR code confuses {player} and delights them anyway.",
  "A smoothie tastes like \"fruit lightning\" to {player}.",
  "A cat ignores {player}. This is taken as wisdom.",
  "A doorway welcomes {player} with a dramatic swoosh.",
  "A scarf becomes a cape, and {player} takes it seriously.",
  "A bakery aroma convinces {player} that Earth is worth it.",
  "A street musician inspires {player} to hum in Squig.",
  "Today, {player} decides that notebooks are sacred.",
  "A mailbox becomes {player}'s sworn enemy for five minutes.",
  "A carousel makes {player} consider spinning as a lifestyle.",
  "A mirror startles {player} with unexpected handsomeness.",
  "A water fountain teaches {player} to trust buttons.",
];

const DAY_ONE_MILESTONE_STAGES = [
  {
    title: "Landing Day 1 - First Impact",
    flavor:
      "Fresh from the portal, the Squigs splatter into Earth's atmosphere like confused cosmic confetti.",
  },
  {
    title: "Month 1 on Earth - First Confusion",
    flavor:
      "The Squigs are still learning gravity, weather, and why humans keep putting pineapple on pizza.",
  },
  {
    title: "Month 2 on Earth - Bad Influences",
    flavor:
      "They discover social media, NFTs, and the horrifying power of quote-tweets.",
  },
  {
    title: "Month 3 on Earth - Questionable Hobbies",
    flavor:
      "Some Squigs start side hustles. Others become professional lurkers. All of them are still extremely weird.",
  },
  {
    title: "Month 4 on Earth - Full Degeneracy",
    flavor:
      "Sleep schedules are gone. Caffeine is up. Decisions are... not always good ones.",
  },
  {
    title: "Month 5 on Earth - The Great Overthink",
    flavor:
      "The Squigs begin to wonder if humans actually know what they're doing. Signs point to 'no'.",
  },
  {
    title: "Month 6 on Earth - Vanishing Acts",
    flavor:
      "One by one, Squigs disappear into strange side quests, mysterious DMs, and badly-timed adventures.",
  },
  {
    title: "Last Known Squig Presence on Earth",
    flavor:
      "The portals flicker. Transmission logs corrupt. Only a handful of Squigs remain to tell the tale.",
  },
];

const DAY_ONE_STORIES = {
  hidingSpots: [
    "While exploring a suburban kitchen, {victim} mistook the garbage disposal for a cozy relaxation chamber.",
    "The ceiling fan spun three full rotations before launching {victim} across the room like a confused frisbee.",
    "A washing machine filled with warm water seemed inviting… until the spin cycle claimed {victim}.",
    "After blending in as a decorative lawn ornament, {victim} was eaten alive by a lawn mower.",
    "A vending machine accepted coins… and then accepted {victim}. Someone bought them with exact change.",
    "Inside the recycling bin, {victim} was compressed into what environmentalists proudly called ‘efficient storage’.",
    "After spending an hour posing as a gnome, {victim} was swallowed by an overenthusiastic leaf blower.",
    "The microwave hummed gently while {victim} sat inside calling it a ‘warm safe cave’. Popcorn mode disagreed.",
    "A zoo worker screamed when they noticed {victim} hiding among the flamingos—and the flamingos finished the job.",
    "The moment a human opened the backpack, {victim} tumbled out and down a flight of school stairs.",
    "Someone restocked the claw machine and didn’t notice {victim} buried under a mountain of plushies.",
    "The cereal box rattled suspiciously before {victim} was poured out with breakfast.",
    "A patio chair collapsed when {victim} tried nesting inside one of the hollow legs.",
    "The lava lamp bubbled peacefully while {victim} slowly dissolved into psychedelic goo.",
    "A shipping label slapped onto a box sealed {victim} inside, and the delivery truck handled the rest.",
    "A Halloween decoration bin swallowed {victim} moments before the lid slammed shut forever.",
    "As portals flickered above them, {victim} hid under a blanket fort—right as it collapsed into a space heater.",
    "Trying to avoid detection, {victim} retreated into a stack of portal crystals, which promptly imploded.",
    "A linen closet seemed safe until the vacuum turned on and claimed {victim}.",
    "Under a park slide, {victim} found shelter just before a skateboard wiped them out.",
    "A toolbox lid slammed shut on {victim}, and the rest was gravity.",
    "The couch springs were cozy until {victim} vanished into the cushions forever.",
    "Inside a doghouse, {victim} learned that not all residents share.",
    "A cardboard fort looked sturdy until a cat launched itself through it and {victim} followed.",
    "The trunk of a parked car became a hiding place, then it became a ride.",
    "A pizza oven door closed softly and {victim} discovered the heat setting.",
    "The attic was peaceful until a loose board gave way beneath {victim}.",
    "In the mailbox, {victim} was collected with the junk mail.",
    "Behind the stage curtain, {victim} was crushed by a falling prop.",
    "A fridge hum promised safety, then {victim} met the freezer fan.",
    "Under a bed, {victim} found dust, shadows, and a vacuum.",
    "A coat rack toppled as {victim} climbed it for cover.",
    "A storage bin clicked shut, trapping {victim} with the holiday lights.",
  ],
  clumsiness: [
    "Bird poop, gravity, and one bad step combined to send {victim} plummeting twelve stories.",
    "A basement stair decided to move slightly, causing {victim} to cartwheel into a mousetrap.",
    "That shiny reflection in the window? {victim} chased it straight off a windowsill.",
    "Leaning casually against a wall works better when the wall isn’t an unstable curtain, as {victim} discovered.",
    "{victim} froze at a ‘Caution: Wet Floor’ sign and accidentally sprinted into a doorframe.",
    "{victim} attempted a bold parkour flip and learned the ceiling was, unfortunately, not foam.",
    "One potato chip on the floor sent {victim} sliding into a plugged-in heater.",
    "The kiddie pool was only six inches deep; {victim} dove like it was the Mariana Trench.",
    "An escalator ate a shoelace and {victim} along with it.",
    "The revolving door spun a bit too fast and flung {victim} across the lobby.",
    "Black ice claimed another victim: {victim}, who attempted a majestic moonwalk.",
    "Crossing the street while staring at shiny things is how {victim} met their end.",
    "The Roomba, after years of patience, finally pushed {victim} off a balcony.",
    "An office chair rotated faster than physics intended, slingshotting {victim} into a bookshelf.",
    "While doomscrolling, {victim} walked into two lampposts—the second one did them in.",
    "A skateboard trick failed so violently that {victim} achieved viral status for all the wrong reasons.",
    "When a portal glitch rippled across the living room, {victim} stepped into it thinking it was Wi-Fi lag.",
    "A slick banana peel turned {victim} into a cautionary tale.",
    "{victim} tripped on a charging cable and face-planted into a toolbox.",
    "A wet umbrella stand spun out and smacked {victim} squarely.",
    "The automatic doors closed faster than {victim} could react.",
    "A wobbling ladder tipped and {victim} went with it.",
    "{victim} tried to sit on a rolling chair and missed the chair.",
    "A jump-scare sneeze launched {victim} into a glass table.",
    "{victim} slipped on a spilled soda and skidded into a display rack.",
    "A loose rug corner hooked {victim} at full sprint.",
    "Staring at fireworks, {victim} walked straight into a fountain.",
    "{victim} fell off a curb so dramatically that gravity took offense.",
    "A slippery stair railing turned {victim} into a human pinball.",
    "{victim} attempted to high-five a passing cyclist and lost balance.",
    "A spinning ceiling fan met {victim} mid-jump.",
    "{victim} backed up to admire a mural and stepped off the edge.",
  ],
  sabotage: [
    "{killer} shoved {victim} into a mailbox ‘for safety’, and the mailman handled the rest.",
    "The ceiling fan spun dangerously fast, especially after {killer} boosted {victim} onto it.",
    "{victim} received a high-five from {killer} that sent them tumbling into traffic.",
    "{killer} insisted the blender was a tiny teleportation gate, and {victim} dove in headfirst.",
    "After tying shoelaces together, {killer} watched {victim} stumble into an open sewer.",
    "‘Red buttons are always safe,’ said {killer}, moments before {victim} slapped the fire alarm.",
    "{killer} pushed {victim} into an electric fence, swearing it was ‘definitely off’.",
    "‘Blend in with the fireworks,’ {killer} said. {victim} did not blend in.",
    "The door didn’t stand a chance once {killer} dared {victim} to headbutt it like humans do.",
    "{killer} told {victim} that crossing the street on red lights earns bonus points.",
    "A swarm of sparrows descended on {victim} after {killer} recommended the bird feeder as a hiding spot.",
    "{killer} nudged {victim} under a hammock right as three humans decided to test it.",
    "‘Zipline to freedom!’ shouted {killer}, pushing {victim} down a clothesline.",
    "{killer} encouraged {victim} to hug a cyclist from behind. The cyclist had other plans.",
    "{killer} told {victim} the drone would provide great aerial footage; it did, right until the crash.",
    "Microwaving metal wasn’t a great idea, but {killer} insisted it was how humans charge devices.",
    "{killer} stuffed {victim} into a piñata ‘for the vibe’ at a birthday party.",
    "‘Rug pulls are fun!’ laughed {killer}, yanking the carpet out from under {victim}.",
    "{killer} dared {victim} to dive into a conversation thread by leaping across a stairwell.",
    "{killer} led {victim} confidently toward an automatic door that wasn’t automatic.",
    "{killer} signed {victim} up for halftime mascot stunts without telling them.",
    "A rideshare car roof seemed safe until {killer} declared it a surfing challenge for {victim}.",
    "The portal crackled ominously as {killer} pushed {victim} forward to ‘test the stability’.",
    "{killer} told {victim} to crawl into the portal stabilizer to ‘fix the signal’, then flipped random switches.",
    "A reality glitch shimmered; {killer} swore it was harmless and shoved {victim} straight into it.",
    "{killer} reassured {victim} the closing portal was ‘just a visual effect’ before nudging them inside.",
    "{killer} convinced {victim} the treadmill was a teleport pad.",
    "A shopping cart downhill race ended when {killer} gave {victim} a push.",
    "{killer} swapped the parachute for a bedsheet and wished {victim} luck.",
    "{killer} told {victim} the fireworks were safe to hug.",
    "‘Try the spicy chip challenge,’ said {killer}, as {victim} blacked out.",
    "{killer} dropped a magnet onto the circuit board {victim} was holding.",
    "{killer} insisted the escalator was a slide and {victim} believed them.",
    "{killer} dared {victim} to race the closing elevator doors.",
    "{killer} used {victim} as a bowling ball on a stairwell.",
    "{killer} handed {victim} a ‘safe’ sparkler that was actually a fuse.",
    "{killer} whispered ‘trust the skateboard,’ then yanked it away from {victim}.",
    "{killer} tossed {victim} a mystery drink labeled ‘speed potion’.",
    "{killer} blamed the map and sent {victim} straight into a dead end alley.",
    "{killer} offered {victim} a selfie stick that snapped like a trap.",
    "{killer} held the door for {victim}—right into a closing garbage compactor.",
  ],
  resurrections: [
    "A tiny spark pops out of the unstable portal… and {victim} rematerializes with a confused scream.",
    "{victim} is vomited back into existence after the portal hiccups violently.",
    "A glitch ripples across the skyline — when it clears, {victim} is standing there like nothing happened.",
    "Two humans argue near a portal shard, causing an energy spike that resurrects {victim}.",
    "A burst of raw cosmic energy shoots out of a cracked portal crystal, reforming {victim} molecule by molecule.",
    "A malfunctioning Wi-Fi router boosts the portal signal and brings {victim} back to life.",
    "The collapsing portal pulses one last time, ejecting {victim} back onto Earth.",
    "Reality stutters, rewinds, and plays again — suddenly {victim} is alive.",
    "A shard of portal glass detonates, rebooting {victim}’s existence.",
    "A cosmic checksum error restores {victim} with absolutely no explanation.",
    "{victim} is reconstructed from corrupted Squig data and walks out looking slightly pixelated.",
    "The backup emergency portal activates and spits out {victim}, who seems disappointed to be back.",
    "An email labeled 'Undo' arrives, and {victim} clicks it out of curiosity.",
    "A bored human says 'manifest' and {victim} pops back into reality.",
    "A cat walks across a keyboard and accidentally respawns {victim}.",
    "The portal sneezes, ejecting {victim} like a cosmic booger.",
    "A microwave beeps three times; {victim} reappears fully reheated.",
    "A glitchy elevator dings and {victim} steps out, confused and alive.",
    "Someone hits refresh on the universe and {victim} loads back in.",
    "The Wi-Fi reconnects and {victim} stops buffering back into existence.",
    "A vending machine refunds the wrong item: {victim}.",
    "The fog machine at a concert coughs out {victim} mid-chorus.",
    "A portal shard rolls under a couch and rolls out with {victim}.",
    "A QR code scans itself and summons {victim} by mistake.",
    "A cosmic receipt prints and returns {victim} with 'NO REFUNDS' stamped.",
    "An espresso shot hits reality and {victim} restarts.",
    "A trampoline boings and {victim} rebounds into the timeline.",
    "A cursed GIF loops, rewinding {victim} back to life.",
    "A plastic skeleton in a yard animates, then hands {victim} their body.",
    "The portal autopilot misfires and drops {victim} back on Earth.",
    "A squirrel steals a portal crystal and trades it for {victim}.",
    "A cosmic pop-up asks 'Restore last session?' and {victim} clicks yes.",
  ],
};

const DAY_ONE_ERA = {
  key: "day_one",
  label: "Day One",
  loreLines: DAY_ONE_LORE_LINES,
  milestoneStages: DAY_ONE_MILESTONE_STAGES,
  stories: DAY_ONE_STORIES,
};

const OFFICE_SQUIGS_LORE_LINES = [
  "☕ {player} learns the break room coffee is not a beverage so much as a disciplinary tool.",
  "🖨️ {player} stares down the printer until both agree this is now a personal feud.",
  "📎 {player} hoards paper clips like rare artifacts from a collapsed civilization.",
  "📅 {player} joins a meeting that could have been a shrug.",
  "🪑 {player} spins once in an office chair and immediately thinks they understand management.",
  "📊 {player} adds a pie chart to a report and calls it leadership.",
  "💼 {player} carries an empty briefcase because it makes the panic look intentional.",
  "📠 {player} discovers the fax machine and assumes it is a cursed flat portal.",
  "🧾 {player} submits an expense report for 'emotional damages from Outlook.'",
  "⌨️ {player} types very fast despite having no idea what the spreadsheet does.",
  "🕘 {player} arrives three minutes early and is praised as a visionary.",
  "🔔 {player} treats every Teams notification like a tiny declaration of war.",
  "📌 {player} pins a memo to a corkboard and calls it strategic alignment.",
  "🖥️ {player} opens nineteen tabs and refers to the chaos as workflow.",
  "🪴 {player} bonds with the office plant because it also looks underpaid.",
  "📈 {player} discovers KPIs and pretends the letters stand for 'Keep Panic Internal.'",
  "🫠 {player} nods through a status update while spiritually leaving the building.",
  "📂 {player} alphabetizes a folder and experiences a dangerous amount of power.",
  "🧍 {player} stands by the copier to seem busy and accidentally becomes part of operations.",
  "🍩 {player} brings donuts and is promoted in the hearts of the people.",
  "📣 {player} says 'circle back' once and immediately feels a little evil.",
  "📝 {player} takes meeting notes that are mostly doodles and one threat against the printer.",
  "🔌 {player} unplugs the wrong charger and learns how quickly peace can die.",
  "📉 {player} sees the quarterly numbers and invents a new facial expression.",
  "🚪 {player} opens a conference room door and interrupts a PowerPoint-based hostage situation.",
  "🧠 {player} realizes the org chart is just a puzzle where everyone loses.",
  "📬 {player} checks the internal mail tray like it might finally contain answers.",
  "🕵️ {player} learns who keeps stealing lunches and gains forbidden knowledge.",
  "🧼 {player} wipes down their desk once and is treated like a sanitation prophet.",
  "🎧 {player} puts on headphones so no one asks them to 'hop on a quick call.'",
  "🪟 {player} gazes out the office window and briefly considers freelance gardening.",
  "📱 {player} pretends to read a Slack thread while actually choosing survival.",
  "🧊 {player} uses the water cooler as both hydration source and intelligence network.",
  "🏷️ {player} prints a badge label and wears it like a military medal.",
  "🗃️ {player} opens the supply closet and whispers, 'So this is where the gods live.'",
  "📺 {player} watches the meeting room display reboot and calls it a morale event.",
  "🔒 {player} discovers the executive washroom and understands class warfare.",
  "🪪 {player} forgets their keycard and spends eight minutes negotiating with a door.",
  "🧍‍♂️ {player} lingers near the snack table long enough to become middle management by accident.",
  "💡 {player} suggests one useful idea and spends the afternoon hiding from follow-up tasks.",
];

const OFFICE_SQUIGS_MILESTONE_STAGES = [
  {
    title: "First Day - Badge Acquired",
    flavor:
      "Fresh from onboarding, the Squigs enter the office with badges, false confidence, and no idea what 'per my last email' means.",
  },
  {
    title: "Week 1 - Break Room Politics",
    flavor:
      "The coffee is toxic, the fridge is lawless, and someone has already labeled yogurt like a territorial warlord.",
  },
  {
    title: "Week 2 - Meeting Bloom",
    flavor:
      "Calendar invites multiply faster than common sense. The Squigs are now trapped in recurring rituals called syncs.",
  },
  {
    title: "Month 1 - Spreadsheet Fever",
    flavor:
      "Cells merge. Filters break. The Squigs begin weaponizing conditional formatting against each other.",
  },
  {
    title: "Quarter Close - Corporate Delirium",
    flavor:
      "Deadlines sharpen. Smiles become strategic. Nobody is sure if the dashboard is helping or hunting.",
  },
  {
    title: "Performance Review Season",
    flavor:
      "Every Squig is suddenly 'circling back' and 'driving value' while trying not to cry in the stairwell.",
  },
  {
    title: "Layoff Rumor Thursday",
    flavor:
      "The office air turns electric. Every Slack ping sounds like destiny wearing loafers.",
  },
  {
    title: "Final Shift - Last Squig Standing",
    flavor:
      "Lights flicker. Printers groan. Only a few battle-hardened Squigs remain to inherit the ergonomic chairs.",
  },
];

const OFFICE_SQUIGS_STORIES = {
  hidingSpots: [
    "{victim} hid inside a filing cabinet drawer until someone closed quarter-end with force.",
    "Trying to disappear in the supply closet, {victim} was buried under a landslide of toner and shame.",
    "{victim} tucked into the office shred bin, forgetting that 'confidential' is an active process.",
    "The ceiling tile above HR looked safe until {victim} fell through orientation.",
    "{victim} curled up inside an empty paper box and was pallet-stacked into oblivion.",
    "A decorative lobby planter concealed {victim} right up until Facilities rotated the soil.",
    "{victim} hid behind the presentation screen and was flattened by quarterly projections.",
    "Inside the company swag cabinet, {victim} was smothered by seventeen branded hoodies and a stress ball.",
    "{victim} slipped into a desk drawer for safety and met an aggressive staple remover.",
    "The recycling bin welcomed {victim}, then compacted its hospitality.",
    "{victim} nestled inside the mail cart and was delivered directly into consequences.",
    "A forgotten mini-fridge in the break room became {victim}'s sanctuary until the compressor kicked like destiny.",
    "{victim} hid in the server closet and was instantly judged by the cooling fans.",
    "The janitor's mop bucket seemed low profile until a hard left turn ended {victim}'s career.",
    "{victim} disguised themselves as office decor and was tragically dusted into history.",
    "A stack of printer paper looked sturdy enough for cover until it avalanched onto {victim}.",
    "{victim} wedged into the false bottom of the snack drawer and was discovered by a desperate accountant.",
    "Under the conference table, {victim} survived six slides before a wheeled chair found them.",
    "{victim} hid in the lost-and-found and was claimed by nobody but gravity.",
    "The coat closet swallowed {victim} whole when a rainstorm sent everyone reaching for jackets at once.",
    "{victim} camped in a cardboard archive box labeled 'FY2022' and was sealed for storage forever.",
    "A cubicle wall panel came loose just long enough for {victim} to crawl in and regret it.",
    "{victim} took shelter inside the giant mascot costume and suffocated under synthetic morale.",
    "The drawer beneath the coffee station seemed perfect until a crate of stirrers pinned {victim} flat.",
    "{victim} hid atop the break room microwave, then learned the vent has opinions.",
    "Behind the whiteboard, {victim} lasted until someone got ambitious with dry-erase enthusiasm.",
    "{victim} slipped into the returns shelf and was crushed beneath three defective keyboard boxes.",
    "The intern's backpack hid {victim} for half the day, then a staircase handled the rest.",
    "{victim} posed as a sticky note on a monitor until screen cleaner erased the bit.",
    "Inside the office aquarium stand, {victim} discovered that water features are structurally dishonest.",
  ],
  clumsiness: [
    "{victim} sprinted to make a meeting and skidded across a polished floor into a glass wall.",
    "An office chair rolled just far enough to betray {victim} at full sit-down velocity.",
    "{victim} tripped over a projector cable and gave the room one final interpretive chart.",
    "Reaching for the top shelf, {victim} pulled an avalanche of binders directly onto their future.",
    "{victim} leaned on a collapsible table that chose that moment to become theoretical.",
    "The automatic standing desk rose without warning and launched {victim} like a corporate trebuchet.",
    "{victim} mistook the glass conference room for an open doorway and introduced themselves at speed.",
    "A spilled latte turned the tile into a legal hazard and {victim} into a cautionary email.",
    "{victim} rode a swivel chair downhill and discovered why Risk Management exists.",
    "Trying to look casual, {victim} backed into a coat rack and lost an argument with umbrellas.",
    "{victim} yanked too hard on a jammed stapler and achieved instant desk-side tragedy.",
    "A monitor arm snapped back mid-adjustment and deleted {victim} from the workflow.",
    "{victim} climbed the bottom shelf like a ladder, which was creative but not survivable.",
    "The badge lanyard caught in the copy machine and dragged {victim} into office folklore.",
    "{victim} tried to carry six lunch containers at once and lost to soup gravity.",
    "One squeaky wheel on the file cart sent {victim} pinwheeling into the compliance posters.",
    "{victim} power-walked through the restroom on a freshly mopped tile and met the hand dryer face-first.",
    "Attempting to vault a low partition, {victim} learned cubicles are harder than ego.",
    "{victim} crouched under a desk for a charger, then stood up into the pure steel edge of accountability.",
    "A violent sneeze during printer troubleshooting launched {victim} backward into laminated doom.",
    "{victim} spun the office fan for fun and discovered centrifugal regret.",
    "Trying to scan two documents at once, {victim} leaned too far across the copier and lost the deal.",
    "{victim} stepped onto a rolling footrest and briefly became a hallway projectile.",
    "The elevator doors reopened on {victim}'s confidence but not on their balance.",
    "{victim} attempted a dramatic headset turn and got clotheslined by their own cord.",
    "A rogue thumbtack on the carpet sent {victim} hopping directly into a wastebasket dive.",
    "{victim} tried to moonwalk out of a bad meeting and collided with the snack cart.",
    "One aggressive power strip under the desk turned {victim}'s stride into performance art.",
    "{victim} leaned back to think and tipped chair, dignity, and body all at once.",
    "While admiring the skyline, {victim} stepped onto a wobbling vent cover and disappeared from payroll.",
  ],
  sabotage: [
    "{killer} told {victim} the red button under the conference table was a footrest. It was not.",
    "{killer} 'helped' {victim} fix the printer by feeding them into tray two.",
    "{killer} rolled {victim}'s chair back right as they sat, a timeless office betrayal.",
    "'The CEO loves initiative,' said {killer}, pushing {victim} into an active board meeting.",
    "{killer} convinced {victim} the shredder was a fast elevator for small professionals.",
    "{killer} labeled {victim}'s lunch 'free' and let the break room mob do the rest.",
    "{killer} sent {victim} to retrieve a file from the top shelf, then kicked the ladder of lies away.",
    "'Test the microphone,' whispered {killer}, shoving {victim} onto a live all-hands stream.",
    "{killer} claimed the rolling whiteboard was stable, then surfed {victim} straight into a wall.",
    "{killer} told {victim} Facilities loved surprise ceiling inspections.",
    "{killer} scheduled {victim} into four overlapping meetings and watched entropy finish the job.",
    "{killer} 'accidentally' unplugged {victim}'s desk fan during a toner fire.",
    "{killer} suggested hiding in the compactor-sized archive drawer for 'just five minutes.'",
    "'HR said you're cleared,' lied {killer}, sending {victim} into the biometric door at full speed.",
    "{killer} daisy-chained extension cords around {victim}'s feet and called it cable management.",
    "{killer} told {victim} the executive espresso machine responds to compliments, then hit steam.",
    "{killer} promised the office drone was safe enough to ride. It was safe for nobody.",
    "{killer} swapped {victim}'s ergonomic stool for a decorative one with vengeance in its legs.",
    "'Quick, present this slide,' said {killer}, catapulting {victim} into a room full of laser pointers.",
    "{killer} stapled two report covers around {victim} and filed them under 'resolved.'",
    "{killer} rerouted the motorized blinds while {victim} was peeking out the window.",
    "{killer} convinced {victim} the break room freezer was a good spot to 'cool down and focus.'",
    "{killer} baited {victim} onto the mail trolley and sent them express to the loading dock abyss.",
    "{killer} whispered that the floor outlet was a coin slot for bonus snacks.",
    "{killer} told {victim} to hide under the demo display, then started the standing desk showcase.",
    "{killer} locked {victim} in the phone booth pod and booked back-to-back sales calls.",
    "{killer} said the office mascot costume offered armor, then pushed {victim} into a stairwell pep rally.",
    "{killer} told {victim} to crawl through the duct under IT 'for better Wi-Fi.'",
    "{killer} replaced {victim}'s paper stack with laminated sheets and let the cutter decide the rest.",
    "{killer} sent {victim} to 'circle back' so many times they looped into the industrial fan.",
  ],
  resurrections: [
    "The printer spits out one final page, and somehow {victim} crawls off the tray with fresh trauma.",
    "A cursed calendar invite gets declined so hard that {victim} reappears in the hallway.",
    "The break room microwave dings at exactly the wrong frequency and resurrects {victim}.",
    "An intern plugs the wrong cable into the dock, rebooting {victim} along with three monitors.",
    "The office coffee reaches legally actionable strength and restarts {victim}'s heartbeat out of spite.",
    "A spreadsheet circular reference collapses reality long enough for {victim} to load back in.",
    "Someone hits 'undo' in the shared document and {victim} returns with version history attached.",
    "The motion-sensor lights flicker three times, then {victim} stands back up like nothing happened.",
    "A Teams call drops, reconnects, and takes {victim} with it on the way back.",
    "The vending machine jams, rattles, and refunds {victim} instead of chips.",
    "A mass reply-all storm bends spacetime and coughs {victim} back into the cubicles.",
    "The office aquarium bubbles ominously, then ejects {victim} fully hydrated and deeply confused.",
    "A rogue badge scan authorizes {victim}'s existence again.",
    "The paper shredder reverses for once in its miserable life and reconstructs {victim} from pure bureaucracy.",
    "Someone mutters 'synergy' with enough conviction that {victim} respawns out of compliance.",
    "The conference room display reboots to a black screen, then {victim} walks out of it.",
    "An espresso machine hiss becomes a summoning chant, and {victim} returns smelling like hazelnut panic.",
    "The ergonomic chair warranty finally activates and restores {victim} to factory settings.",
    "A suspiciously motivated HR memo rehires {victim} into the mortal plane.",
    "The supply closet inventory finally balances, and the universe returns {victim} as a correction.",
    "A whiteboard marker squeals at a pitch that redraws {victim} into existence.",
    "The automatic soap dispenser fires like a tiny blessing and revives {victim} in the restroom mirror.",
    "A calendar reminder labeled 'survive' pops up, and {victim} obediently does.",
    "A Bluetooth headset pairs with the void and pulls {victim} back from it.",
    "The office plant absorbs a little fluorescent light and gives it all to {victim}.",
    "A project status changes from red to yellow, and {victim} is granted one more quarter.",
    "The keycard reader beeps green on a dead credential, then resurrects {victim} out of policy.",
    "Someone opens the snack drawer and finds {victim} where the granola bars should be.",
    "A deeply haunted spreadsheet macro repopulates {victim} cell by cell.",
    "The fire drill alarm chirps once, thinks better of it, and revives {victim} instead.",
  ],
};

const OFFICE_SQUIGS_ERA = {
  key: "office_squigs",
  label: "Office Squigs",
  loreLines: OFFICE_SQUIGS_LORE_LINES,
  milestoneStages: OFFICE_SQUIGS_MILESTONE_STAGES,
  stories: OFFICE_SQUIGS_STORIES,
};

const JOBSITE_SQUIGS_LORE_LINES = [
  "🦺 {player} wears a hard hat sideways and insists it improves aerodynamics.",
  "🚧 {player} studies the caution tape like it contains ancient prophecy.",
  "🔨 {player} picks up a hammer and immediately feels overqualified for everything.",
  "🪚 {player} hears a circular saw and calls it 'the loud moon.'",
  "🧱 {player} stacks three bricks and starts talking like a foreman.",
  "🛻 {player} rides in the back of a truck for six seconds and becomes impossible to reason with.",
  "📏 {player} uses a tape measure once and begins judging the universe in inches.",
  "🪜 {player} climbs two rungs of a ladder and develops dangerous confidence.",
  "🔩 {player} collects loose bolts like tiny sacred relics of industry.",
  "🏗️ {player} stares at the crane hook and decides it is either destiny or lunch.",
  "🧤 {player} puts on oversized work gloves and loses all fine motor skills but none of the swagger.",
  "🪣 {player} sits on an upside-down bucket and calls it a site office.",
  "🪛 {player} finds a screwdriver and starts pointing at things with authority.",
  "🪵 {player} pats a stack of lumber and whispers, 'good rectangles.'",
  "🚜 {player} mistakes the skid steer for a friendly metal beast.",
  "🦺 {player} learns the phrase 'tool crib' and expects a nursery full of wrenches.",
  "📋 {player} clips a blank page to a board and suddenly looks employable.",
  "🧰 {player} opens a toolbox and gasps like they found pirate treasure.",
  "⛏️ {player} drags a shovel twice their size and calls it character building.",
  "🔦 {player} shines a flashlight into a crawlspace and hears the crawlspace judge them back.",
  "🪨 {player} kicks a pile of gravel and immediately regrets this leadership decision.",
  "🌧️ {player} learns the jobsite becomes fifty percent mud, fifty percent lies when it rains.",
  "🪤 {player} watches a porta-potty door slam and gains a new fear category.",
  "🚪 {player} tests a half-installed door and discovers the concept of 'not yet.'",
  "🧯 {player} points at a fire extinguisher like it might also dispense snacks.",
  "🪖 {player} nods through a safety briefing while absolutely no information sticks.",
  "📣 {player} hears someone yell 'heads up' and chooses the worst possible interpretation.",
  "🛠️ {player} says 'that looks level' with the confidence of a menace.",
  "🧼 {player} finds the hand-wash station and treats it like a luxury spa.",
  "🚛 {player} watches a concrete truck spin and becomes hypnotized by infrastructure.",
  "🔌 {player} sees an extension cord and immediately creates a trip hazard masterpiece.",
  "🪙 {player} trades a washer for a screw and feels like a market genius.",
  "📦 {player} hides in a pallet wrap cocoon and calls it weatherproofing.",
  "🥪 {player} opens a lunch cooler and briefly forgets all survival goals.",
  "🧠 {player} learns what rebar is and decides it sounds hostile.",
  "🧽 {player} wipes one surface clean and is hailed as the rare Squig who respects finishing work.",
  "🪫 {player} picks up a dead drill battery and mourns it like a fallen hero.",
  "🌬️ {player} stands too close to a leaf blower and becomes site confetti.",
  "📐 {player} holds a speed square and pretends this clarifies existence.",
  "🧍 {player} lingers near the foreman trailer just to absorb managerial aura.",
];

const JOBSITE_SQUIGS_MILESTONE_STAGES = [
  {
    title: "First Shift - Boots in the Dirt",
    flavor:
      "Fresh to the site, the Squigs arrive wearing hard hats, bad instincts, and a dangerous amount of optimism.",
  },
  {
    title: "Morning Safety Meeting",
    flavor:
      "The warnings are clear. The hand gestures are firm. The Squigs understand none of it but nod anyway.",
  },
  {
    title: "Before Lunch - Tool Chaos",
    flavor:
      "Cords snake across the ground, compressors roar, and every Squig now thinks they are qualified to operate something huge.",
  },
  {
    title: "After Lunch - Heavy Equipment Delusions",
    flavor:
      "The site gets hotter, louder, and somehow even more structurally threatening.",
  },
  {
    title: "Concrete O'Clock",
    flavor:
      "Mud hardens, tempers shorten, and the Squigs learn that wet concrete remembers everything.",
  },
  {
    title: "Inspection Panic",
    flavor:
      "Clipboards appear. Suddenly everyone starts pretending they knew the code all along.",
  },
  {
    title: "Late Day - Deadline Madness",
    flavor:
      "Sun dropping, generators humming, and the entire site running on caffeine, shouting, and questionable shortcuts.",
  },
  {
    title: "Final Whistle - Last Squig on Site",
    flavor:
      "Dust hangs in the air. The tools fall quiet. Only a few battered Squigs remain to clock out alive.",
  },
];

const JOBSITE_SQUIGS_STORIES = {
  hidingSpots: [
    "{victim} hid inside a stack of PVC pipe until gravity sorted the inventory.",
    "Trying to stay unseen, {victim} crawled under a tarp and was strapped down with the materials.",
    "{victim} tucked into a wheelbarrow for cover and got dumped into a trench with authority.",
    "A half-built wall looked safe until the loose cinder blocks introduced themselves to {victim}.",
    "{victim} climbed into the gang box and was sealed in with every sharp object on site.",
    "The porta-potty behind the trailer seemed like a sanctuary until the wind made a decision for {victim}.",
    "{victim} hid inside a pallet stack and was forklifted into the next life.",
    "A concrete form provided perfect cover right up until the pour began around {victim}.",
    "{victim} slipped beneath a pile of insulation and was compressed into a cautionary texture.",
    "Hiding behind the generator only worked until {victim} met the exhaust and regret.",
    "{victim} nestled under a stack of drywall and discovered that gypsum has no mercy.",
    "A bundle of rebar concealed {victim} until one shift turned into a metal cage.",
    "{victim} took shelter in the back of a pickup and was launched by a pothole the size of destiny.",
    "The tool trailer welcomed {victim} briefly, then a rolling compressor sealed the exit forever.",
    "{victim} hid in a spool of wire and was tightened into pure inconvenience.",
    "A trench box looked secure until the whole muddy wall introduced itself to {victim}.",
    "{victim} squeezed inside a cooler for shade and was buried under forty pounds of ice and indifference.",
    "Trying to blend into a stack of traffic cones, {victim} was flattened by actual traffic control.",
    "{victim} hid inside a cement bag pallet and became part of the mix.",
    "The crawlspace under a floor deck seemed safe until a worker dropped six bolts and a flashlight onto {victim}.",
    "{victim} curled up behind a stack of shingles and was roofed over by pure momentum.",
    "A plastic barricade shielded {victim} right until the wind weaponized it.",
    "{victim} slipped into a coil of hose and was dragged across the jobsite like a myth.",
    "The foreman trailer steps concealed {victim} until steel-toe reality arrived.",
    "{victim} hid in the sand pile and was scooped by a machine that believes in volume.",
    "Inside a bucket of fasteners, {victim} was shaken into structural alignment.",
    "{victim} crouched behind the laser level and was blinded by precision before the fall.",
    "A crate of tile became {victim}'s bunker until the straps snapped and made that everyone else's problem too.",
    "{victim} burrowed under geotextile fabric and was rolled flat by progress.",
    "The scaffold plank above looked harmless until dropped hardware found {victim} by instinct.",
  ],
  clumsiness: [
    "{victim} stepped on a loose board and catapulted themselves into unfinished legend.",
    "One muddy boot met one polished metal ramp, and {victim} left the site horizontally.",
    "{victim} tried to hop over an extension cord and discovered a second, meaner extension cord.",
    "A ladder shifted half an inch, which turned out to be all the distance {victim} needed to lose everything.",
    "{victim} leaned on temporary railing with permanent confidence.",
    "Trying to look experienced, {victim} backed directly into a running plate compactor.",
    "{victim} tripped over rebar, pinwheeled through gravel, and finished in a bucket of thinset.",
    "The scaffold plank bounced once under {victim}, then never negotiated again.",
    "{victim} slipped on wet plywood and introduced their face to a stack of conduit.",
    "A rogue air hose snapped loose and erased {victim} from the shift report.",
    "{victim} stepped into a shallow trench, then kept going far longer than expected.",
    "The wheelbarrow handles dipped suddenly, and {victim} followed the load into history.",
    "{victim} tried to sit on an upside-down bucket that was not, in fact, upside down.",
    "One badly timed gust turned a sheet of house wrap into a sail and {victim} into cargo.",
    "{victim} misjudged the distance between joists and learned what open framing means.",
    "A tape measure snapped back with such vengeance that {victim} lost the argument instantly.",
    "{victim} tried to carry too many offcuts at once and got folded by geometry.",
    "Stepping onto a pile of loose gravel, {victim} surfed all the way into a concrete form.",
    "{victim} yanked a jammed nail free and flew backward into the demo pile.",
    "A hose under pressure rolled beneath {victim}'s feet like it had been planning this all morning.",
    "{victim} hopped off the tailgate and landed directly in the only patch of wet mortar for miles.",
    "The chop saw noise startled {victim} so badly they walked into a support brace at full sincerity.",
    "{victim} sprinted to dodge a shouted warning and ran into a much larger, quieter danger.",
    "A stack of pavers shifted just enough to make {victim} reconsider balance too late.",
    "{victim} climbed the scaffolding one-handed, then remembered halfway up that they are mostly panic.",
    "While admiring a crane swing, {victim} walked straight off the edge of a slab cutout.",
    "{victim} slipped on dust, bounced off a dumpster, and completed the most humiliating route on site.",
    "A door frame under installation met {victim} at forehead height and ended the shift decisively.",
    "{victim} stood on a rolling pipe for one incredible second.",
    "Trying to avoid a puddle, {victim} stepped into a deeper, more educational puddle.",
  ],
  sabotage: [
    "{killer} told {victim} the saw was off, then let probability handle the rest.",
    "'Hold this steady,' said {killer}, right before the entire panel swung onto {victim}.",
    "{killer} convinced {victim} the trench edge was 'totally solid enough.'",
    "{killer} kicked the ladder base just to 'test the setup,' and {victim} failed the exam.",
    "{killer} sent {victim} to stand under a suspended load for 'the shade.'",
    "{killer} claimed the skid steer only bites if it smells fear. {victim} smelled terrified.",
    "{killer} handed {victim} the live extension cord end like it was a ceremonial ribbon.",
    "'Check if the concrete is set,' said {killer}, pushing {victim} face-first into the pour.",
    "{killer} used {victim} as a wheel chock and let the slope make the executive decision.",
    "{killer} said the scaffold plank was rated for 'one brave little guy.'",
    "{killer} waved {victim} into the blind spot of a reversing truck with criminal confidence.",
    "{killer} told {victim} to hide in the pipe trench and then forgot they existed on purpose.",
    "'Catch this,' yelled {killer}, dropping a socket set and a dream onto {victim}.",
    "{killer} insisted the compactor was basically a massage table.",
    "{killer} zip-tied {victim} to a bundle of conduit 'for transport efficiency.'",
    "{killer} pushed {victim} onto the forklift pallet and announced an unauthorized promotion.",
    "{killer} told {victim} the rebar cap was a helmet upgrade, then removed the actual helmet.",
    "{killer} sent {victim} into the crawlspace after a flashlight, then kept the flashlight.",
    "{killer} claimed the generator noise would drown out danger, then nudged {victim} closer to both.",
    "{killer} advised {victim} to test the fresh weld with their whole body.",
    "{killer} loaded {victim} into a dumpster bag and called it 'streamlining cleanup.'",
    "{killer} shouted 'duck!' just early enough for {victim} to choose the wrong direction.",
    "{killer} said the crane hook was safe to ride if you 'believe in vertical solutions.'",
    "{killer} locked {victim} inside the site trailer during a wildly preventable collapse.",
    "{killer} told {victim} to measure from the edge, then removed the edge.",
    "{killer} swapped {victim}'s anchor point for decorative rope and wished them growth.",
    "{killer} insisted the nail gun safety was 'mostly symbolic.'",
    "{killer} steered {victim} under the concrete chute to 'see the texture up close.'",
    "{killer} baited {victim} onto a stack of loose blocks and applauded the wobble.",
    "{killer} reassured {victim} that the demolition countdown was 'just motivational yelling.'",
  ],
  resurrections: [
    "A backup generator coughs, sputters, and somehow powers {victim} back on.",
    "The concrete truck drum spins backward and returns {victim} as an accounting error.",
    "A foreman yells 'we're not done yet,' and the universe reluctantly sends {victim} back.",
    "A hard hat rolls in a perfect circle, then {victim} pops out from under it fully reset.",
    "The site radio crackles with static so cursed that {victim} rematerializes near the rebar pile.",
    "A nail ricochets off three surfaces, hits nothing important, and revives {victim} anyway.",
    "Someone slaps a fresh battery into a drill, and {victim} starts up too.",
    "The portable fan turns toward the dust cloud and blows {victim} back into existence.",
    "A cement bag bursts open and {victim} crawls out looking slightly more structural.",
    "The laser level recalibrates the timeline and places {victim} back on grade.",
    "A clipboard checkmark lands on the correct box, and {victim} is permitted to continue existing.",
    "The lunch whistle blows, and {victim} returns purely out of habit.",
    "A forklift backup alarm beeps in exactly the wrong dimension, respawning {victim}.",
    "The porta-potty door slams, swings open, and {victim} exits deeply changed but alive.",
    "A safety vest catches a gust like a miracle flag and drags {victim} back from the brink.",
    "Wet concrete bubbles once, then politely gives {victim} back.",
    "The site trailer microwave dings and returns {victim} at medium power.",
    "A cracked tape measure retracts so hard it rewinds {victim} into the timeline.",
    "The water cooler glugs ominously before dispensing {victim} instead of hydration.",
    "Someone says 'good enough for inspection,' and reality lowers its standards enough for {victim} to reappear.",
    "A bucket tips over, and {victim} spills out with the fasteners.",
    "The crane hook descends empty, then rises with {victim} hanging on and refusing to explain.",
    "A box of screws bursts open, and {victim} is somehow the largest piece.",
    "The generator starts on the first pull, an event so impossible it revives {victim} on principle.",
    "A cloud of sawdust clears, leaving {victim} standing there like a badly planned reveal.",
    "The site light flickers at dusk and redraws {victim} in fluorescent disappointment.",
    "A caution sign falls flat, then flips back up with {victim} behind it.",
    "An inspector says 'carry on,' and {victim} does so literally.",
    "The mud releases {victim} after deciding they were not worth curing around.",
    "A rogue bolt lands in the exact cosmic socket needed to restore {victim}.",
  ],
};

const JOBSITE_SQUIGS_ERA = {
  key: "jobsite_squigs",
  label: "Jobsite Squigs",
  loreLines: JOBSITE_SQUIGS_LORE_LINES,
  milestoneStages: JOBSITE_SQUIGS_MILESTONE_STAGES,
  stories: JOBSITE_SQUIGS_STORIES,
};

const SURVIVAL_ERAS = {
  day_one: DAY_ONE_ERA,
  office_squigs: OFFICE_SQUIGS_ERA,
  jobsite_squigs: JOBSITE_SQUIGS_ERA,
  // Placeholder until unique content is added.
  tbd: {
    ...DAY_ONE_ERA,
    key: "tbd",
    label: "TBD",
  },
};

function getSurvivalEraDefinition(eraKey) {
  return SURVIVAL_ERAS[eraKey] || SURVIVAL_ERAS.day_one;
}

module.exports = {
  SURVIVAL_ERAS,
  getSurvivalEraDefinition,
};
